[Metadata]
# Name[ca]=Per defecte
# Name[da]=Standard
# Name[de]=Standard
# Name[fr]=Par défaut
# Name[ja]=デフォルト
# Name[ka]=ნაგულისხმევი
# Name[ko]=기본값
# Name[ru]=По умолчанию
# Name[sv]=Standard
# Name[vi]=Mặc định
# Name[zh_CN]=默认
# Name[zh_TW]=預設
Name=Dracula
Version=1
Author=xuqiang
Description=Dracula Theme
ScaleWithDPI=True

[InputPanel]
NormalColor=#f8f8f2
HighlightCandidateColor=#ff79c6
HighlightColor=#ff79c6
HighlightBackgroundColor=#44475a
# | 值                 | 含义         |
# | ----------------- | ---------- |
# | `Top`             | 放在候选框顶部    |
# | `First Candidate` | 与第一个候选项对齐  |
# | `Center`          | 候选列表中间     |
# | `Last Candidate`  | 与最后一个候选项对齐 |
# | `Bottom`          | 放在候选框底部    |
# PageButtonAlignment=Last Candidate
PageButtonAlignment=Center

[InputPanel/TextMargin]
# Left=5
# Right=5
# Top=5
# Bottom=5
Left=10
Right=10
Top=6
Bottom=6

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
# Color=#282a36
# BorderColor=#44475a
# BorderWidth=2
Image=panel.svg

[InputPanel/Background/Margin]
# Left=2
# Right=2
# Top=2
# Bottom=2
Left=10
Right=10
Top=10
Bottom=10

[InputPanel/Highlight]
# Color=#44475a
Image=highlight.svg

[InputPanel/Highlight/Margin]
# Left=5
# Right=5
# Top=5
# Bottom=5
Left=10
Right=10
Top=6
Bottom=6

[InputPanel/PrevPage]
Image=prevpage.svg

[InputPanel/PrevPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[InputPanel/NextPage]
Image=nextpage.svg

[InputPanel/NextPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[Menu]
NormalColor=#f8f8f2
HighlightCandidateColor=#f8f8f2

[Menu/Background]
Color=#282a36
BorderColor=#44475a
BorderWidth=2

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/CheckBox]
Image=radio.svg

[Menu/SubMenu]
Image=arrow.svg

[Menu/Highlight]
Color=#44475a

[Menu/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu/Separator]
Color=#6272a4

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[AccentColorField]
0=Input Panel Border
1=Input Panel Highlight Candidate Background
2=Input Panel Highlight
3=Menu Border
4=Menu Separator
5=Menu Selected Item Background
